version: "3"

services:
  nginx:
    container_name: nginx-server
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - example-network
    
  db:
    container_name: db
    image: postgres:alpine
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myDb
    networks:
      - example-network
  
  app:
    container_name: app
    build: ..
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - example-network  

networks:
  example-network:
    name: example-network

